name: tanveer_portfolio
description: "Personal Portfolio Website of Tanveer Ahmad - Flutter Developer & Software Engineer"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  web: ^1.1.1
  emailjs: ^4.0.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
